name: Test schedule

on:
  workflow_dispatch:
    inputs:
      myvar: 
        default: "Hello World!"
        type: string
        

  schedule:
    - cron: '*/2 * * * *'
  
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
      - name: Echo the message
        run: echo "${{ inputs.myvar }}"
  